name: trackGUI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools
  - wheel
  - pip:
      - beautifulsoup4==4.14.3
      - certifi==2026.5.20
      - charset-normalizer==3.4.7
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.19.1
      - filterpy==1.4.5
      - flatbuffers==25.12.19
      - fonttools==4.60.2
      - gdown==5.2.2
      - humanfriendly==10.0
      - idna==3.16
      - imageio==2.37.2
      - imgviz==1.7.6
      - importlib-resources==6.5.2
      - joblib==1.5.3
      - kiwisolver==1.4.7
      - lazy-loader==0.5
      - loguru==0.7.3
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.2.1
      - numpy==2.0.2
      - onnxruntime==1.19.2
      - opencv-contrib-python==4.13.0.92
      - opencv-python==4.13.0.92
      - packaging==26.2
      - pillow==11.3.0
      - protobuf==6.33.6
      - pyparsing==3.3.2
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.19
      - pyqt5-sip==12.17.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - qtpy==2.4.3
      - requests==2.32.5
      - ruff==0.15.14
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - soupsieve==2.8.4
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tqdm==4.67.3
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - zipp==3.23.1
